### ISSUE TITLE
bug: Segfault after upgrading dependencies

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#712]
**Describe the bug**
The daemon `nanocld` segfault while trying to connect to the database.

Complete backtrace:

```sh
[2023-12-10T21:11:08Z INFO ] nanocld_x86_64_stable_v0.12.0:670cf331eab5186fb19e23d2799913a2578964fd                                                                                            
[New Thread 0x7ffff6da76c0 (LWP 349475)]
[New Thread 0x7ffff6ba66c0 (LWP 349476)]
[2023-12-10T21:11:08Z DEBUG] set_unix_permission
[New Thread 0x7ffff69a56c0 (LWP 349478)]
[Detaching after vfork from child process 349477]
[2023-12-10T21:11:08Z DEBUG] /run/nanocl doesn't exists cannot change unix socket permission
[2023-12-10T21:11:08Z ERROR] Failed to spawn crond: No such file or directory (os error 2)
[2023-12-10T21:11:08Z INFO ] Connecting to store at: store.nanocl.internal:26258
[New Thread 0x7ffff67a46c0 (LWP 349479)]
[New Thread 0x7ffff65a36c0 (LWP 349481)]
[New Thread 0x7ffff63a26c0 (LWP 349482)]
[New Thread 0x7ffff61a16c0 (LWP 349483)]
free(): invalid pointer
free(): invalid pointer
free(): invalid pointer

Thread 6 "r2d2-worker-0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff65a36c0 (LWP 349481)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_kill.c.                                                                                               
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c42866 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c268b7 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7c27750 in __libc_message (fmt=fmt@entry=0x7ffff7dc3b34 "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#6  0x00007ffff7ca3c67 in malloc_printerr (str=str@entry=0x7ffff7dc1612 "free(): invalid pointer") at ./malloc/malloc.c:5765
#7  0x00007ffff7ca5ea4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4500
#8  0x00007ffff7ca87f3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007ffff7f5dabe in freePGconn (conn=0x7fffe4001230) at /usr/src/postgresql-15-15.5-0ubuntu0.23.10.1/build/../src/interfaces/libpq/fe-connect.c:4090
#10 0x0000555556947518 in diesel::pg::connection::raw::RawConnection::establish (
    database_url="postgresql://root:root@store.nanocl.internal:26258/defaultdb?sslmode=verify-full&sslcert=/home/leone/.nanocl_dev/state/store/certs/client.root.crt&sslkey=/home/leone/.nanocl_dev/state/store/certs/clie"...) at src/pg/connection/raw.rs:41
#11 0x0000555556931c01 in diesel::pg::connection::{impl#3}::establish (
    database_url="postgresql://root:root@store.nanocl.internal:26258/defaultdb?sslmode=verify-full&sslcert=/home/leone/.nanocl_dev/state/store/certs/client.root.crt&sslkey=/home/leone/.nanocl_dev/state/store/certs/clie"...) at src/pg/connection/mod.rs:161
#12 0x0000555555aae1a9 in diesel::r2d2::{impl#5}::connect<diesel::pg::connection::PgConnection> (self=0x7fffec001c08)
    at /home/leone/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.1.4/src/r2d2.rs:191
#13 0x0000555555f52e92 in r2d2::add_connection::inner::{closure#0}<diesel::r2d2::ConnectionManager<diesel::pg::connection::PgConnection>> ()
    at /home/leone/.cargo/registry/src/index.crates.io-6f17d22bba15001f/r2d2-0.8.10/src/lib.rs:241
#14 0x00005555559e00de in core::ops::function::FnOnce::call_once<r2d2::add_connection::inner::{closure_env#0}<diesel::r2d2::ConnectionManager<diesel::pg::connection::PgConnection>>, ()> ()
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250
#15 0x0000555556963008 in alloc::boxed::{impl#47}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> (self=..., args=())
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007
#16 0x000055555695f138 in scheduled_thread_pool::Worker::run_job (self=0x7ffff65a2560, job=...) at src/lib.rs:426
#17 0x000055555695eb2f in scheduled_thread_pool::{impl#8}::run::{closure#0} () at src/lib.rs:381
#18 0x0000555556957400 in core::panic::unwind_safe::{impl#23}::call_once<(), scheduled_thread_pool::{impl#8}::run::{closure_env#0}> (self=...)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271
#19 0x000055555695781b in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<scheduled_thread_pool::{impl#8}::run::{closure_env#0}>, ()> (data=0x7ffff65a2350)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504
#20 0x000055555695aecb in __rust_try ()
#21 0x0000555556957712 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<scheduled_thread_pool::{impl#8}::run::{closure_env#0}>> (f=...)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468
#22 0x000055555695763a in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<scheduled_thread_pool::{impl#8}::run::{closure_env#0}>, ()> (
    f=<error reading variable: Cannot access memory at address 0x55520>) at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142
#23 0x000055555695eac6 in scheduled_thread_pool::Worker::run (self=0x7ffff65a2560) at src/lib.rs:381
#24 0x000055555695e970 in scheduled_thread_pool::{impl#8}::start::{closure#0} () at src/lib.rs:375
#25 0x000055555695761e in std::sys_common::backtrace::__rust_begin_short_backtrace<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()> (f=...)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154
#26 0x000055555695bccb in std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure#0}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()> ()
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529
#27 0x000055555695743f in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()>> (self=...) at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271
#28 0x000055555695783c in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()>>, ()> (data=0x7ffff65a2630) at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504
#29 0x000055555695aecb in __rust_try ()
#30 0x000055555695767a in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()>>> (f=...) at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468
#31 0x000055555695bb18 in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()>>, ()> (f=...) at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142
#32 std::thread::{impl#0}::spawn_unchecked_::{closure#1}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()> ()
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528
#33 0x0000555556957e0f in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<scheduled_thread_pool::{impl#8}::start::{closure_env#0}, ()>, ()> ()
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250
#34 0x00005555579791e5 in alloc::boxed::{impl#47}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
#35 alloc::boxed::{impl#47}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> ()
    at library/alloc/src/boxed.rs:2007
#36 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:108
#37 0x00007ffff7c97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#38 0x00007ffff7d2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

```

**To Reproduce**

If we upgrade theses dependencies:

```sh
$   cargo update
    Updating crates.io index
    Updating anstream v0.6.4 -> v0.6.5
    Updating anstyle-query v1.0.1 -> v1.0.2
    Updating dirs v4.0.0 -> v5.0.1
    Updating dirs-sys v0.3.7 -> v0.4.1
    Updating http-body v0.4.5 -> v0.4.6
    Updating itoa v1.0.9 -> v1.0.10
    Updating libc v0.2.150 -> v0.2.151
    Updating ntex-io v0.3.13 -> v0.3.14
    Updating openssl-src v300.1.6+3.1.4 -> v300.2.0+3.2.0
      Adding option-ext v0.2.0
    Updating rust-embed v8.0.0 -> v8.1.0
    Updating rust-embed-impl v8.0.0 -> v8.1.0
    Updating rust-embed-utils v8.0.0 -> v8.1.0
    Updating rustix v0.38.27 -> v0.38.28
    Updating rustls v0.21.9 -> v0.21.10
    Updating ryu v1.0.15 -> v1.0.16
    Updating shellexpand v2.1.2 -> v3.1.0
    Updating tokio v1.34.0 -> v1.35.0
    Updating zerocopy v0.7.29 -> v0.7.30
    Updating zerocopy-derive v0.7.29 -> v0.7.30
```
and run as usual

**Expected behavior**

No Segfault ?

**Additional context**

If we remove the SSL/TLS connection to the database, everything seems to work fine.

**Comment by 0xle0ne** [comment]
This have been fixed by dodging openssl in favor of rustls, i'll keep it open in case it pop again.
